AGR: AGR::cKmeansClustering Class Reference
AGR::cKmeansClustering
AGR::cKmeansClustering Class Reference
cKmeansClustering class.
#include <KmeansClustering.h>
Public Member Functions
cKmeansClustering ()
~cKmeansClustering ()
cClustering * createCopy ()
int createClusters (const cMovement *movementArray, const unsigned int nbMovement)
int closerCluster (const cVector3int &point) const
int clusterise (const cMovement &movement, unsigned int *observation) const
Detailed Description
cKmeansClustering class.
Definition at line 23 of file KmeansClustering.h.
Constructor & Destructor Documentation
AGR::cKmeansClustering::cKmeansClustering ()
Constructor
Definition at line 22 of file KmeansClustering.cpp.
Referenced by createCopy().
AGR::cKmeansClustering::~cKmeansClustering ()
Destructor
Definition at line 30 of file KmeansClustering.cpp.
References AGR::cClustering::m_buffer.
Member Function Documentation
cClustering * AGR::cKmeansClustering::createCopy () [virtual]
Create a copy of the object
Note:
An allocation is done for the created object, which need to be deleted by the used
Implements AGR::cClustering.
Definition at line 40 of file KmeansClustering.cpp.
References cKmeansClustering().
int AGR::cKmeansClustering::createClusters (const cMovement * movementArray, const unsigned int nbMovement) [virtual]
Perform the kmean algorithm
Returns:
-1 if failed. The number of clustering iteration otherwith
Parameters:
movementArray Array of movement used for creating clusters
nbMovement Number of movement in the array
Implements AGR::cClustering.
Definition at line 114 of file KmeansClustering.cpp.
References clusterise(), AGR::cClustering::createNormalisedVectors(), AGR::cMovement::getData(), AGR::cMovement::getSize(), AGR::cClustering::m_buffer, AGR::cClustering::m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
int AGR::cKmeansClustering::closerCluster (const cVector3int & point) const [virtual]
Find the closer cluster of a point
Returns:
-1 if failed. The closer cluster id if success
Parameters:
point Point to be analysed
Implements AGR::cClustering.
Definition at line 51 of file KmeansClustering.cpp.
References AGR::cClustering::m_buffer, AGR::cClustering::m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by clusterise().
int AGR::cKmeansClustering::clusterise (const cMovement & movement, unsigned int * observation) const [virtual]
Clusterise the observation vector
Returns:
-1 if failed. 0 if observation has not changed, 1 if observation has changed
Parameters:
movement Movement to be clusterised
observation Output cluster observation sequence
Implements AGR::cClustering.
Definition at line 81 of file KmeansClustering.cpp.
References closerCluster(), AGR::cMovement::getData(), AGR::cMovement::getSize(), and AGR::cClustering::m_buffer.
Referenced by createClusters().
The documentation for this class was generated from the following files:
latest/include/KmeansClustering.h
latest/src/KmeansClustering.cpp