AGR: AGR::cHMM Class Reference
AGR::cHMM
AGR::cHMM Class Reference
cHMM class.
#include <HMM.h>
Public Member Functions
cHMM ()
cHMM (const cHMM &original)
~cHMM ()
void clear ()
bool initialise (const unsigned int nbHiddenStates, const cVocabulary *vocabulary)
bool isReady () const
bool copy (const cHMM &original)
bool load (const char *fileName)
bool save (const char *fileName, const bool binary=false) const
bool assignVocabulary (const cVocabulary *vocabulary)
bool createHMM (cClustering *clusterer, const cMovement *movementArray, const unsigned int nbMovement)
bool BaumWelch (const cMovement *movementArray, const unsigned int nbMovement, unsigned int sizeObservation=0)
bool BaumWelchClusterised (unsigned int **observationArray, const unsigned int nbObservation, const unsigned int sizeObservation)
float forward (const cMovement &movement, unsigned int normaliseSize=0) const
float forwardClusterised (const unsigned int *observation, const unsigned int observationSize) const
const cVocabulary * getVocabulary () const
unsigned int getObservationSize () const
float getMeanProbabilityWeighted () const
float getVarianceProbabilityWeighted () const
void computeObservationSequence (const cMovement &movement, unsigned int *observation, const unsigned int normaliseSize=0) const
Protected Member Functions
void computeAlpha (float **alpha, const unsigned int *observation, const unsigned int observationSize) const
void computeBeta (float **beta, const unsigned int *observation, const unsigned int observationSize) const
float computeGamma (const unsigned int state, const unsigned int time, float **alpha, float **beta) const
float computeXi (const unsigned int state1, const unsigned int state2, const unsigned int time, float **alpha, float **beta, const unsigned int *observation) const
bool loadASCII (std::ifstream &file)
bool saveASCII (std::ofstream &file) const
bool loadBinary (std::ifstream &file)
bool saveBinary (std::ofstream &file) const
bool computeMeanVariance (unsigned int **observationArray, const unsigned int nbObservation, const unsigned int sizeObservation)
Protected Attributes
unsigned int m_numberStates
const cVocabulary * m_ptVocabulary
unsigned int m_vocabularySize
unsigned int m_observationSize
float m_meanProbabilityWeighted
float m_varianceProbabilityWeighted
float * m_PI
float ** m_A
float ** m_B
Friends
class ::cTestHMM
class cGestureRecogniser
Detailed Description
cHMM class.
Definition at line 27 of file HMM.h.
Constructor & Destructor Documentation
AGR::cHMM::cHMM ()
Constructor
Definition at line 26 of file HMM.cpp.
AGR::cHMM::cHMM (const cHMM & original)
Copy constructor
Parameters:
original cHMM object to be copied
Definition at line 36 of file HMM.cpp.
References AGR::cVocabulary::getSize(), isReady(), m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, m_varianceProbabilityWeighted, and m_vocabularySize.
AGR::cHMM::~cHMM ()
Destructor
Definition at line 73 of file HMM.cpp.
References clear().
Member Function Documentation
void AGR::cHMM::clear ()
Clear all the data
Definition at line 82 of file HMM.cpp.
References m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, m_varianceProbabilityWeighted, and m_vocabularySize.
Referenced by copy(), loadASCII(), loadBinary(), AGR::cGestureRecogniser::loadGesture(), AGR::cGestureRecogniser::removeGesture(), and ~cHMM().
bool AGR::cHMM::initialise (const unsigned int nbHiddenStates, const cVocabulary * vocabulary)
Initialise the data
Definition at line 284 of file HMM.cpp.
References m_numberStates, and m_ptVocabulary.
bool AGR::cHMM::isReady () const
Inform if the HMM is fully initialised and trained, ready to be used.
Returns:
True if ready, false if not
Definition at line 266 of file HMM.cpp.
References m_A, m_B, m_numberStates, m_PI, and m_ptVocabulary.
Referenced by AGR::cGestureRecogniser::addGesture(), BaumWelch(), BaumWelchClusterised(), cHMM(), copy(), forward(), forwardClusterised(), AGR::cGestureRecogniser::gestureLikelihood(), AGR::cGestureRecogniser::gesturesLikelihood(), AGR::cGestureRecogniser::recognise(), AGR::cGestureRecogniser::recogniseGesture(), and save().
bool AGR::cHMM::copy (const cHMM & original)
Copy a cHMM object
Returns:
Success. May fails if the original object is not fully created.
Parameters:
original cHMM object to be copied
Definition at line 126 of file HMM.cpp.
References clear(), AGR::cVocabulary::getSize(), isReady(), m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, m_varianceProbabilityWeighted, and m_vocabularySize.
Referenced by AGR::cGestureRecogniser::resize().
bool AGR::cHMM::load (const char * fileName)
Load an HMM file.
Returns:
Success
Note:
Does not load the vocabulary object, which need to be loaded separatly using cHMM::assignVocabulary()
Parameters:
fileName Name of the file to read into
Definition at line 165 of file HMM.cpp.
References loadASCII(), and loadBinary().
bool AGR::cHMM::save (const char * fileName, const bool binary = false) const
Save an HMM file.
Returns:
Success
Note:
Does not save the vocabulary object
Parameters:
fileName Name of the file to save into
binary Specify whether saving in binary of ASCII format
Definition at line 209 of file HMM.cpp.
References isReady(), saveASCII(), and saveBinary().
Referenced by AGR::cGestureRecogniser::saveGesture().
bool AGR::cHMM::assignVocabulary (const cVocabulary * vocabulary)
Assign a vocabulary to the HMM.
Returns:
Success
Note:
This function should be used for assigning a vocabulary object when loading from files
Definition at line 247 of file HMM.cpp.
References AGR::cVocabulary::getSize(), m_ptVocabulary, and m_vocabularySize.
Referenced by AGR::cGestureRecogniser::addGesture(), AGR::cGestureRecogniser::loadASCII(), AGR::cGestureRecogniser::loadBinary(), and AGR::cGestureRecogniser::resize().
bool AGR::cHMM::createHMM (cClustering * clusterer, const cMovement * movementArray, const unsigned int nbMovement)
Create the cluster and initialise the values from statistics
The HMM is created (PI, A and B buffers are created and initialised). Initials values are using statistics from a set of movement clusterised two times, firstly in a new set of cluster representing the hidden states, secondly using the vocabulary representing the observations sequences. Using these values, statistics are used in order to initialise PI, A and B. The clusterised representation of the Hidden models are only temporary for this function, the vocabulary is after the only clustering method used.
Returns:
Success
Parameters:
clusterer Cluster method used to create HMM clusters
movementArray Array of movement used for initialising the HMM values
nbMovement Number of movement in the array
Definition at line 716 of file HMM.cpp.
References AGR::cMovement::changeVectorSize(), AGR::cClustering::clear(), AGR::cClustering::closerCluster(), AGR::cVocabulary::clusterise(), AGR::cClustering::clusterise(), computeMeanVariance(), AGR::cClustering::createClusters(), AGR::cClustering::createNormalisedVectors(), AGR::cMovement::getData(), AGR::cMovement::getSize(), AGR::cVocabulary::getSize(), AGR::cMovement::initialise(), AGR::cClustering::initialise(), AGR::cVocabulary::isReady(), m_A, m_B, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, and m_vocabularySize.
bool AGR::cHMM::BaumWelch (const cMovement * movementArray, const unsigned int nbMovement, unsigned int sizeObservation = 0)
BaumWelch maximum expectation algorithm
The movement are clusterised in a sizeObservation clusters observation sequence before being sent to the BaumWelchClusterised function.
See also:
BaumWelchClusterised
Returns:
Success
Parameters:
movementArray Movements array to be processed
nbMovement Number of movement in the array
sizeObservation Size of the observation sequence to be created, 0 to use the gesture observation size
Definition at line 407 of file HMM.cpp.
References BaumWelchClusterised(), AGR::cMovement::changeVectorSize(), AGR::cVocabulary::clusterise(), AGR::cMovement::initialise(), isReady(), m_observationSize, and m_ptVocabulary.
bool AGR::cHMM::BaumWelchClusterised (unsigned int ** observationArray, const unsigned int nbObservation, const unsigned int sizeObservation)
BaumWelch maximum expectation algorithm on a vocabulary clusterised observation sequence
Returns:
success
Parameters:
observationArray Observations array to be processed
nbObservation Number of observations in the array
sizeObservation Size of the observation sequence
Definition at line 457 of file HMM.cpp.
References computeAlpha(), computeBeta(), computeGamma(), computeMeanVariance(), computeXi(), AGR::cVocabulary::getSize(), isReady(), m_A, m_B, m_numberStates, m_PI, m_ptVocabulary, and m_vocabularySize.
Referenced by BaumWelch().
float AGR::cHMM::forward (const cMovement & movement, unsigned int normaliseSize = 0) const
Compute the movement observation likelihood probability
Note:
The observation will be clusterised into a cluster buffer of size normaliseSize before being subject to the forward algorithm
If normaliseSize is set to 0, the function will use the HMM's observation size if this one is greater than 0, otherwise the movement size
Returns:
Forward probability for the input movement
Parameters:
movement Movement to be processed
normaliseSize Size of the observation which will be created, see function's note
Definition at line 308 of file HMM.cpp.
References computeObservationSequence(), forwardClusterised(), AGR::cMovement::getSize(), isReady(), and m_observationSize.
Referenced by AGR::cGestureRecogniser::closerGesture(), AGR::cGestureRecogniser::gestureLikelihood(), AGR::cGestureRecogniser::gesturesLikelihood(), AGR::cGestureRecogniser::recognise(), and AGR::cGestureRecogniser::recogniseGesture().
float AGR::cHMM::forwardClusterised (const unsigned int * observation, const unsigned int observationSize) const
Compute the observation likelihood probability
Note:
If normaliseSize is set to 0, the function will use the HMM's observation size if this one is greater than 0, otherwise the movement size
Returns:
Forward probability for the input movement
Parameters:
observation Observation to be processed
observationSize Size of the observation
Definition at line 355 of file HMM.cpp.
References computeAlpha(), isReady(), and m_numberStates.
Referenced by computeMeanVariance(), and forward().
const cVocabulary* AGR::cHMM::getVocabulary () const [inline]
Vocabulary size accessor
Returns:
The vocabulary object pointer
Definition at line 74 of file HMM.h.
References m_ptVocabulary.
Referenced by AGR::cGestureRecogniser::addGesture().
unsigned int AGR::cHMM::getObservationSize () const [inline]
Get the expected observation size for this HMM
Returns:
The expected observation size
Definition at line 82 of file HMM.h.
References m_observationSize.
Referenced by AGR::cGestureRecogniser::closerGesture(), AGR::cGestureRecogniser::gestureLikelihood(), AGR::cGestureRecogniser::gesturesLikelihood(), AGR::cGestureRecogniser::recognise(), and AGR::cGestureRecogniser::recogniseGesture().
float AGR::cHMM::getMeanProbabilityWeighted () const [inline]
Get the mean probability weighted
Note:
This value is set when using createHMM or a BaumWelch function and is normalised by the observation's size used in those function. Using default value (=m_observationSize) is recommanded
Returns:
The mean probability weighted
Definition at line 92 of file HMM.h.
References m_meanProbabilityWeighted.
Referenced by AGR::cGestureRecogniser::isRecognised().
float AGR::cHMM::getVarianceProbabilityWeighted () const [inline]
Get the variance probability weighted
Note:
This value is set when using createHMM or a BaumWelch function and is normalised by the observation's size used in those function. Using default value (=m_observationSize) is recommanded
Returns:
The variance probability weighted
Definition at line 102 of file HMM.h.
References m_varianceProbabilityWeighted.
Referenced by AGR::cGestureRecogniser::isRecognised().
void AGR::cHMM::computeObservationSequence (const cMovement & movement, unsigned int * observation, const unsigned int normaliseSize = 0) const
Compute the observation sequence
Parameters:
movement Movement to be vocabulary clusterised
observation Store the observation sequence generated
normaliseSize Observation size, set 0 if using the movement size
Definition at line 928 of file HMM.cpp.
References AGR::cMovement::changeVectorSize(), AGR::cVocabulary::closerCluster(), AGR::cMovement::getData(), AGR::cMovement::getSize(), AGR::cMovement::initialise(), and m_ptVocabulary.
Referenced by forward().
void AGR::cHMM::computeAlpha (float ** alpha, const unsigned int * observation, const unsigned int observationSize) const [protected]
Compute the alpha component using the forward algorithm
Parameters:
alpha Output alpha buffer
observation Observation to be processed
observationSize Observation size
Definition at line 957 of file HMM.cpp.
References m_A, m_B, m_numberStates, and m_PI.
Referenced by BaumWelchClusterised(), and forwardClusterised().
void AGR::cHMM::computeBeta (float ** beta, const unsigned int * observation, const unsigned int observationSize) const [protected]
Compute the beta component using the backward algorithm
Parameters:
beta Output beta buffer
observation Observation to be processed
observationSize Observation size
Definition at line 987 of file HMM.cpp.
References m_A, m_B, and m_numberStates.
Referenced by BaumWelchClusterised().
float AGR::cHMM::computeGamma (const unsigned int state, const unsigned int time, float ** alpha, float ** beta) const [protected]
Compute the expected state occupancy count (Gamma)
Returns:
The expected state occupancy count (Gamma)
Parameters:
state State
time Time
alpha Alpha, from the forward algorithm
beta Beta, from the forward algorithm
Definition at line 1017 of file HMM.cpp.
References m_numberStates.
Referenced by BaumWelchClusterised().
float AGR::cHMM::computeXi (const unsigned int state1, const unsigned int state2, const unsigned int time, float ** alpha, float ** beta, const unsigned int * observation) const [protected]
Compute the expected state transition count (Xi)
Returns:
The expected state transition count
Parameters:
state1 State 1
state2 State 2
time Time
alpha Alpha, from the forward algorithm
beta Beta, from the forward algorithm
observation Observation sequence
Definition at line 1042 of file HMM.cpp.
References m_A, m_B, and m_numberStates.
Referenced by BaumWelchClusterised().
bool AGR::cHMM::loadASCII (std::ifstream & file) [protected]
Load from an ASCII file
Note:
The vocabulary is not loaded there
Returns:
Success
Definition at line 1125 of file HMM.cpp.
References clear(), m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, m_varianceProbabilityWeighted, and m_vocabularySize.
Referenced by load(), and AGR::cGestureRecogniser::loadASCII().
bool AGR::cHMM::saveASCII (std::ofstream & file) const [protected]
Save from an ASCII file
Returns:
Success
Definition at line 1232 of file HMM.cpp.
References AGR::cVocabulary::getSize(), m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, and m_varianceProbabilityWeighted.
Referenced by save(), and AGR::cGestureRecogniser::saveASCII().
bool AGR::cHMM::loadBinary (std::ifstream & file) [protected]
Load from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 1295 of file HMM.cpp.
References clear(), m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_ptVocabulary, m_varianceProbabilityWeighted, and m_vocabularySize.
Referenced by load(), and AGR::cGestureRecogniser::loadBinary().
bool AGR::cHMM::saveBinary (std::ofstream & file) const [protected]
Save from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 1405 of file HMM.cpp.
References m_A, m_B, m_meanProbabilityWeighted, m_numberStates, m_observationSize, m_PI, m_varianceProbabilityWeighted, and m_vocabularySize.
Referenced by save(), and AGR::cGestureRecogniser::saveBinary().
bool AGR::cHMM::computeMeanVariance (unsigned int ** observationArray, const unsigned int nbObservation, const unsigned int sizeObservation) [protected]
Compute the mean and the variance
Note:
The probability used in this function is weighted by the observation size
The variance is not actually the probability-weighted average of the squared deviations from the mean, after that the value is square rooted => The variance here is the square root probability-weighted average of the squared deviations from the mean.
Returns:
Success
Parameters:
observationArray Observations array to be processed
nbObservation Number of observations in the array
sizeObservation Size of the observation sequence
Definition at line 1076 of file HMM.cpp.
References forwardClusterised(), m_meanProbabilityWeighted, and m_varianceProbabilityWeighted.
Referenced by BaumWelchClusterised(), and createHMM().
Member Data Documentation
unsigned int AGR::cHMM::m_numberStates [protected]
Number of hidden states
Definition at line 142 of file HMM.h.
Referenced by BaumWelchClusterised(), cHMM(), clear(), computeAlpha(), computeBeta(), computeGamma(), computeXi(), copy(), createHMM(), forwardClusterised(), initialise(), isReady(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
const cVocabulary* AGR::cHMM::m_ptVocabulary [protected]
HMM Vocabulary
Definition at line 143 of file HMM.h.
Referenced by assignVocabulary(), BaumWelch(), BaumWelchClusterised(), cHMM(), clear(), computeObservationSequence(), copy(), createHMM(), getVocabulary(), initialise(), isReady(), loadASCII(), loadBinary(), and saveASCII().
unsigned int AGR::cHMM::m_vocabularySize [protected]
Size of the vocabulary, for checking compatibility
Definition at line 144 of file HMM.h.
Referenced by assignVocabulary(), BaumWelchClusterised(), cHMM(), clear(), copy(), createHMM(), loadASCII(), loadBinary(), and saveBinary().
unsigned int AGR::cHMM::m_observationSize [protected]
Size of an observation vector
Definition at line 146 of file HMM.h.
Referenced by BaumWelch(), cHMM(), clear(), copy(), createHMM(), forward(), getObservationSize(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
float AGR::cHMM::m_meanProbabilityWeighted [protected]
Mean probability of weighted observations probability
Definition at line 147 of file HMM.h.
Referenced by cHMM(), clear(), computeMeanVariance(), copy(), getMeanProbabilityWeighted(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
float AGR::cHMM::m_varianceProbabilityWeighted [protected]
Variance probability of weighted observations probability (see computeMeanVariance() note)
Definition at line 148 of file HMM.h.
Referenced by cHMM(), clear(), computeMeanVariance(), copy(), getVarianceProbabilityWeighted(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
float* AGR::cHMM::m_PI [protected]
Initial probability distribution, size = m_numberStates
Definition at line 150 of file HMM.h.
Referenced by BaumWelchClusterised(), cHMM(), clear(), computeAlpha(), copy(), createHMM(), isReady(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
float** AGR::cHMM::m_A [protected]
Transition probability matrix, size = m_numberStates*m_numberStates
Definition at line 151 of file HMM.h.
Referenced by BaumWelchClusterised(), cHMM(), clear(), computeAlpha(), computeBeta(), computeXi(), copy(), createHMM(), isReady(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
float** AGR::cHMM::m_B [protected]
Emission probability matrix, size = m_numberStates*m_ptVocabulary->size()
Definition at line 152 of file HMM.h.
Referenced by BaumWelchClusterised(), cHMM(), clear(), computeAlpha(), computeBeta(), computeXi(), copy(), createHMM(), isReady(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
The documentation for this class was generated from the following files:
latest/include/HMM.h
latest/src/HMM.cpp