AGR: AGR::cVocabulary Class Reference
AGR::cVocabulary
AGR::cVocabulary Class Reference
cVocabulary class.
#include <Vocabulary.h>
Public Member Functions
cVocabulary ()
cVocabulary (const cVocabulary &original)
~cVocabulary ()
void clear ()
bool initialise (cClustering *ptClusterer, const unsigned int size, const cVector3int *buffer=NULL)
bool isReady () const
bool copy (const cVocabulary &original)
bool load (const char *fileName)
bool save (const char *fileName, const bool binary=false) const
int createClusters (const cMovement *movementArray, const unsigned int nbMovement)
int clusterise (const cMovement &movement, unsigned int *observation) const
int closerCluster (const cVector3int &point) const
unsigned int getSize () const
const cVector3int * getBuffer () const
Protected Member Functions
bool loadASCII (std::ifstream &file)
bool saveASCII (std::ofstream &file) const
bool loadBinary (std::ifstream &file)
bool saveBinary (std::ofstream &file) const
Protected Attributes
cClustering * m_clusters
cVector3int * m_buffer
unsigned int m_size
Friends
class ::cTestVocabulary
class cGestureRecogniser
Detailed Description
cVocabulary class.
Definition at line 27 of file Vocabulary.h.
Constructor & Destructor Documentation
AGR::cVocabulary::cVocabulary ()
Constructor
Definition at line 25 of file Vocabulary.cpp.
AGR::cVocabulary::cVocabulary (const cVocabulary & original)
Copy constructor
Parameters:
original cVocabulary object to be copied
Definition at line 33 of file Vocabulary.cpp.
References AGR::cClustering::createCopy(), AGR::cClustering::initialise(), m_buffer, m_clusters, and m_size.
AGR::cVocabulary::~cVocabulary ()
Destructor
Definition at line 47 of file Vocabulary.cpp.
References clear().
Member Function Documentation
void AGR::cVocabulary::clear ()
Clear all the data
Definition at line 56 of file Vocabulary.cpp.
References m_buffer, m_clusters, and m_size.
Referenced by loadASCII(), AGR::cGestureRecogniser::loadVocabulary(), AGR::cGestureRecogniser::removeVocabulary(), and ~cVocabulary().
bool AGR::cVocabulary::initialise (cClustering * ptClusterer, const unsigned int size, const cVector3int * buffer = NULL)
Initialise the vocabulary
Returns:
Success
Parameters:
ptClusterer Cluster object to be used by m_clusters
size Size of the buffer, the number of clusters
buffer Values for initialising the buffer (NULL if not needed)
Definition at line 74 of file Vocabulary.cpp.
References AGR::cClustering::createCopy(), AGR::cClustering::initialise(), m_buffer, m_clusters, and m_size.
bool AGR::cVocabulary::isReady () const
Inform if the vocabulary is ready to be used.
Returns:
True if ready, false if not
Note:
The function does not take into account if the clusters are created
Definition at line 211 of file Vocabulary.cpp.
References m_buffer, and m_clusters.
Referenced by AGR::cGestureRecogniser::addVocabulary(), copy(), AGR::cHMM::createHMM(), and save().
bool AGR::cVocabulary::copy (const cVocabulary & original)
Copy a vocabulary object
Parameters:
original cVocabulary object to be copied
Definition at line 105 of file Vocabulary.cpp.
References AGR::cClustering::createCopy(), AGR::cClustering::initialise(), isReady(), m_buffer, m_clusters, and m_size.
Referenced by AGR::cGestureRecogniser::resize().
bool AGR::cVocabulary::load (const char * fileName)
Load an vocabulary file.
Returns:
Success
Parameters:
fileName Name of the file to read into
Definition at line 131 of file Vocabulary.cpp.
References loadASCII(), and loadBinary().
bool AGR::cVocabulary::save (const char * fileName, const bool binary = false) const
Save an vocabulary file.
Returns:
Success
Parameters:
fileName Name of the file to save into
binary Specify whether saving in binary of ASCII format
Definition at line 173 of file Vocabulary.cpp.
References isReady(), saveASCII(), and saveBinary().
Referenced by AGR::cGestureRecogniser::saveVocabulary().
int AGR::cVocabulary::createClusters (const cMovement * movementArray, const unsigned int nbMovement)
Launch the cClustering createClusters() function
Returns:
-1 if failed. The number of clustering iteration otherwith
Parameters:
movementArray Array of movement used for creating clusters
nbMovement Number of movement in the array
Definition at line 227 of file Vocabulary.cpp.
References AGR::cClustering::createClusters(), and m_clusters.
int AGR::cVocabulary::clusterise (const cMovement & movement, unsigned int * observation) const
Launch the cClustering clusterise() function
Returns:
-1 if failed. 0 if obsClusterArray has not changed, 1 if obsClusterArray has changed
Parameters:
movement Movement to be clusterised
observation Output cluster observation sequence
Definition at line 242 of file Vocabulary.cpp.
References AGR::cClustering::clusterise(), and m_clusters.
Referenced by AGR::cHMM::BaumWelch(), and AGR::cHMM::createHMM().
int AGR::cVocabulary::closerCluster (const cVector3int & point) const
Launch the cClustering closerCluster() function
Returns:
-1 if failed. The closer cluster id if success
Parameters:
point Point to be analysed
Definition at line 258 of file Vocabulary.cpp.
References AGR::cClustering::closerCluster(), and m_clusters.
Referenced by AGR::cHMM::computeObservationSequence().
unsigned int AGR::cVocabulary::getSize () const [inline]
Buffer size accessor
Returns:
The buffer size
Definition at line 55 of file Vocabulary.h.
References m_size.
Referenced by AGR::cHMM::assignVocabulary(), AGR::cHMM::BaumWelchClusterised(), AGR::cHMM::cHMM(), AGR::cHMM::copy(), AGR::cHMM::createHMM(), and AGR::cHMM::saveASCII().
const cVector3int* AGR::cVocabulary::getBuffer () const [inline]
Get the buffer for reading only
Returns:
The buffer (read only)
Definition at line 63 of file Vocabulary.h.
References m_buffer.
bool AGR::cVocabulary::loadASCII (std::ifstream & file) [protected]
Load from an ASCII file
Note:
The vocabulary is not loaded there
Returns:
Success
Definition at line 274 of file Vocabulary.cpp.
References clear(), AGR::cClustering::initialise(), m_buffer, m_clusters, m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by load(), and AGR::cGestureRecogniser::loadASCII().
bool AGR::cVocabulary::saveASCII (std::ofstream & file) const [protected]
Save from an ASCII file
Returns:
Success
Definition at line 324 of file Vocabulary.cpp.
References m_buffer, m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by save(), and AGR::cGestureRecogniser::saveASCII().
bool AGR::cVocabulary::loadBinary (std::ifstream & file) [protected]
Load from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 357 of file Vocabulary.cpp.
References AGR::cClustering::initialise(), m_buffer, m_clusters, m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by load(), and AGR::cGestureRecogniser::loadBinary().
bool AGR::cVocabulary::saveBinary (std::ofstream & file) const [protected]
Save from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 423 of file Vocabulary.cpp.
References m_buffer, and m_size.
Referenced by save(), and AGR::cGestureRecogniser::saveBinary().
Member Data Documentation
cClustering* AGR::cVocabulary::m_clusters [protected]
Clustering object
Definition at line 72 of file Vocabulary.h.
Referenced by clear(), closerCluster(), clusterise(), copy(), createClusters(), cVocabulary(), initialise(), isReady(), loadASCII(), and loadBinary().
cVector3int* AGR::cVocabulary::m_buffer [protected]
Buffer containing the vocabulary data, used by m_clusters
Definition at line 73 of file Vocabulary.h.
Referenced by clear(), copy(), cVocabulary(), getBuffer(), initialise(), isReady(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
unsigned int AGR::cVocabulary::m_size [protected]
Size of the buffer
Definition at line 74 of file Vocabulary.h.
Referenced by clear(), copy(), cVocabulary(), getSize(), initialise(), loadASCII(), loadBinary(), saveASCII(), and saveBinary().
The documentation for this class was generated from the following files:
latest/include/Vocabulary.h
latest/src/Vocabulary.cpp