AGR: AGR::cMovement Class Reference
AGR::cMovement
AGR::cMovement Class Reference
cMovement class.
#include <Movement.h>
Public Member Functions
cMovement ()
cMovement (const cMovement &original)
~cMovement ()
void clear ()
bool initialise (const std::vector< cVector3int > &inMove)
bool initialise (const unsigned int size, const cVector3int *vectorArray=NULL)
bool copy (const cMovement &original)
unsigned int getSize () const
const cVector3int getData (const unsigned int id) const
const cVector3int * getBuffer () const
cVector3int * modifyBuffer ()
Static Public Member Functions
static bool changeVectorSize (const cMovement &inputMovement, const unsigned int newSize, cMovement *ptOutputMovement)
Protected Attributes
cVector3int * m_buffer
unsigned int m_size
Friends
class ::cTestMovement
Detailed Description
cMovement class.
Definition at line 64 of file Movement.h.
Constructor & Destructor Documentation
AGR::cMovement::cMovement ()
Constructor
Definition at line 180 of file Movement.cpp.
AGR::cMovement::cMovement (const cMovement & original)
Copy constructor
Definition at line 188 of file Movement.cpp.
References m_buffer, and m_size.
AGR::cMovement::~cMovement ()
Destructor
Definition at line 206 of file Movement.cpp.
References clear().
Member Function Documentation
void AGR::cMovement::clear ()
Clear all the data
Definition at line 238 of file Movement.cpp.
References m_buffer, and m_size.
Referenced by ~cMovement().
bool AGR::cMovement::initialise (const std::vector< cVector3int > & inMove)
Initialisation using the STL vector container
Parameters:
inMove std::vector containing the list of cVector3int to be copied
Returns:
Success
Definition at line 253 of file Movement.cpp.
References AGR::cVector3int::copyTo(), m_buffer, and m_size.
Referenced by AGR::cHMM::BaumWelch(), AGR::cHMM::computeObservationSequence(), AGR::cHMM::createHMM(), AGR::cClustering::createNormalisedVectors(), AGR::cMovementRecogniser::getMovement(), and AGR::cMovementRecogniser::manualRecognitionStop().
bool AGR::cMovement::initialise (const unsigned int size, const cVector3int * vectorArray = NULL)
Initialisation using a buffer
Returns:
Success
Parameters:
size Size of the movement
vectorArray Array containing the initial value, set NULL if not needed
Definition at line 284 of file Movement.cpp.
References m_buffer, and m_size.
bool AGR::cMovement::copy (const cMovement & original)
Clear all the data
Definition at line 215 of file Movement.cpp.
References m_buffer, and m_size.
bool AGR::cMovement::changeVectorSize (const cMovement & inputMovement, const unsigned int newSize, cMovement * ptOutputMovement) [static]
Change the size of a movement
Note:
OutputVector buffer will be created automatically if needed
The function have better results if input movements are positive (see note in the code)
Returns:
Success
Parameters:
inputMovement Input movement used as model
newSize Size of the new vector
ptOutputMovement Output vector resized
Definition at line 313 of file Movement.cpp.
References getSize(), m_buffer, m_size, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by AGR::cHMM::BaumWelch(), AGR::cHMM::computeObservationSequence(), AGR::cHMM::createHMM(), and AGR::cClustering::createNormalisedVectors().
unsigned int AGR::cMovement::getSize () const [inline]
Buffer size accessor
Returns:
The buffer size
Definition at line 88 of file Movement.h.
References m_size.
Referenced by changeVectorSize(), AGR::cGestureRecogniser::closerGesture(), AGR::cKmeansClustering::clusterise(), AGR::cHMM::computeObservationSequence(), AGR::cKmeansClustering::createClusters(), AGR::cHMM::createHMM(), AGR::cClustering::createNormalisedVectors(), AGR::cHMM::forward(), AGR::cGestureRecogniser::gestureLikelihood(), AGR::cGestureRecogniser::recognise(), and AGR::cGestureRecogniser::recogniseGesture().
const cVector3int AGR::cMovement::getData (const unsigned int id) const [inline]
Get a value from the buffer
Returns:
A buffer value (read only)
Parameters:
id index of the data in the buffer
Definition at line 96 of file Movement.h.
References m_buffer, and m_size.
Referenced by AGR::cKmeansClustering::clusterise(), AGR::cHMM::computeObservationSequence(), AGR::cKmeansClustering::createClusters(), AGR::cHMM::createHMM(), and AGR::cClustering::createNormalisedVectors().
const cVector3int* AGR::cMovement::getBuffer () const [inline]
Get the buffer for reading only
Returns:
The buffer (read only)
Definition at line 108 of file Movement.h.
References m_buffer.
cVector3int* AGR::cMovement::modifyBuffer () [inline]
Get The buffer for modifications
Returns:
The buffer
Definition at line 116 of file Movement.h.
References m_buffer.
Referenced by AGR::cClustering::createNormalisedVectors().
Member Data Documentation
cVector3int* AGR::cMovement::m_buffer [protected]
Buffer containing the movement data
Definition at line 126 of file Movement.h.
Referenced by changeVectorSize(), clear(), cMovement(), copy(), getBuffer(), getData(), initialise(), and modifyBuffer().
unsigned int AGR::cMovement::m_size [protected]
Size of the buffer (number of cVector3int)
Definition at line 127 of file Movement.h.
Referenced by changeVectorSize(), clear(), cMovement(), copy(), getData(), getSize(), and initialise().
The documentation for this class was generated from the following files:
latest/include/Movement.h
latest/src/Movement.cpp