AGR: AGR::cGestureRecogniser Class Reference
AGR::cGestureRecogniser
AGR::cGestureRecogniser Class Reference
Gesture recogniser class.
#include <GestureRecogniser.h>
Public Member Functions
cGestureRecogniser ()
~cGestureRecogniser ()
void clear ()
bool init (unsigned int nbVocabulary, unsigned int nbGestures)
bool isReady () const
bool load (const char *fileName)
bool save (const char *fileName, const bool binary=false) const
bool resize (unsigned int newVocabularyBufferSize, unsigned int newGestureBufferSize)
unsigned int getNumberGesture ()
unsigned int getNumberVocabulary ()
tGestureId recognise (const cMovement &movement) const
bool recogniseGesture (const tGestureId gestureId, const cMovement &movement) const
tGestureId closerGesture (const cMovement &movement) const
float gestureLikelihood (const tGestureId gestureId, const cMovement &movement) const
bool gesturesLikelihood (const cMovement &movement, float *probabilityVector) const
tGestureId addGesture (const cGesture &gesture, tVocabularyId vocabularyId=-1, const char *gestureName=NULL)
tGestureId loadGesture (const char *gestureFile, tVocabularyId vocabularyId, const char *gestureName=NULL)
bool saveGesture (const tGestureId gestureId, const char *gestureFile, const bool binary=false) const
bool removeGesture (const tGestureId gestureId)
cGesture * getGesture (const tGestureId gestureId) const
const char * getGestureName (const tGestureId gestureId) const
tGestureId findGestureByName (const char *gestureName) const
tVocabularyId addVocabulary (const cVocabulary &vocabulary, const char *vocName=NULL)
tVocabularyId loadVocabulary (const char *vocabularyFile, const char *vocName=NULL)
bool saveVocabulary (const tVocabularyId vocabularyId, const char *vocabularyFile, const bool binary=false) const
bool removeVocabulary (const tVocabularyId vocabularyId)
cVocabulary * getVocabulary (const tVocabularyId vocabularyId) const
const char * getVocabularyName (const tVocabularyId vocabularyId) const
tVocabularyId findVocabularyByName (const char *vocName) const
cMovementRecogniser * getMovementRecogniser ()
Protected Member Functions
bool loadASCII (std::ifstream &file)
bool saveASCII (std::ofstream &file) const
bool loadBinary (std::ifstream &file)
bool saveBinary (std::ofstream &file) const
bool isRecognised (const cGesture &gesture, const float probability) const
Protected Attributes
cVocabulary * m_vocabularyBuffer
cGesture * m_gestureBuffer
char ** m_vocabularyNameBuffer
char ** m_gestureNameBuffer
unsigned int m_vocabularySize
unsigned int m_gestureSize
cMovementRecogniser m_movementRecogniser
Friends
class ::cTestGestureRecogniser
Detailed Description
Gesture recogniser class.
This class is the main Accelerometer Gesture Recognition class.
Definition at line 49 of file GestureRecogniser.h.
Constructor & Destructor Documentation
AGR::cGestureRecogniser::cGestureRecogniser ()
Constructor
Definition at line 21 of file GestureRecogniser.cpp.
AGR::cGestureRecogniser::~cGestureRecogniser ()
Destructor
Definition at line 35 of file GestureRecogniser.cpp.
References clear().
Member Function Documentation
void AGR::cGestureRecogniser::clear ()
Clear all the data
Definition at line 44 of file GestureRecogniser.cpp.
References AGR::cMovementRecogniser::clear(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_movementRecogniser, m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
Referenced by init(), loadASCII(), and ~cGestureRecogniser().
bool AGR::cGestureRecogniser::init (unsigned int nbVocabulary, unsigned int nbGestures)
Initialise the gesture recogniser object
Returns:
Success
Parameters:
nbVocabulary Number of vacabulary to be used
nbGestures Number of gestures to be used
Definition at line 93 of file GestureRecogniser.cpp.
References clear(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
bool AGR::cGestureRecogniser::isReady () const
Inform if the vocabulary is ready to be used.
Returns:
True if ready, false if not
Definition at line 124 of file GestureRecogniser.cpp.
References m_gestureBuffer, and m_vocabularyBuffer.
Referenced by addGesture(), addVocabulary(), closerGesture(), loadGesture(), loadVocabulary(), removeGesture(), removeVocabulary(), resize(), save(), saveASCII(), and saveBinary().
bool AGR::cGestureRecogniser::load (const char * fileName)
Load a cGestureRecogniser object from a file
Returns:
Success
Parameters:
fileName Name of the file to read into
Definition at line 139 of file GestureRecogniser.cpp.
References loadASCII(), and loadBinary().
Referenced by loadGesture(), and loadVocabulary().
bool AGR::cGestureRecogniser::save (const char * fileName, const bool binary = false) const
Save a cGestureRecogniser object to a file
Returns:
Success
Parameters:
fileName Name of the file to save into
binary Specify whether saving in binary of ASCII format
Definition at line 182 of file GestureRecogniser.cpp.
References isReady(), saveASCII(), and saveBinary().
bool AGR::cGestureRecogniser::resize (unsigned int newVocabularyBufferSize, unsigned int newGestureBufferSize)
Resize the gesture and vocabulary buffers
Note:
Set the values to 0 to adjust the buffer to the numbers of object actually stored and ready
Returns:
Success
Parameters:
newVocabularyBufferSize Size of the new vocabulary buffer (0 for the actual number of vocabulary ready)
newGestureBufferSize Size of the new gesture buffer (0 for the actual number of gesture ready)
Definition at line 220 of file GestureRecogniser.cpp.
References AGR::cHMM::assignVocabulary(), AGR::cHMM::copy(), AGR::cVocabulary::copy(), getVocabulary(), isReady(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
unsigned int AGR::cGestureRecogniser::getNumberGesture ()
Return the number of gestures objects
Returns:
the number of gestures objects
Definition at line 367 of file GestureRecogniser.cpp.
References m_gestureSize.
unsigned int AGR::cGestureRecogniser::getNumberVocabulary ()
Return the number of vocabulary objects
Returns:
the number of vocabulary objects
Definition at line 377 of file GestureRecogniser.cpp.
References m_vocabularySize.
tGestureId AGR::cGestureRecogniser::recognise (const cMovement & movement) const
Get the id of the recognised gesture if any
Returns:
-1 if failed, otherwise the id of the recognised gesture
Parameters:
movement Movement to be analysed
Definition at line 876 of file GestureRecogniser.cpp.
References AGR::cHMM::forward(), getGesture(), AGR::cHMM::getObservationSize(), AGR::cMovement::getSize(), AGR::cHMM::isReady(), isRecognised(), and m_gestureSize.
bool AGR::cGestureRecogniser::recogniseGesture (const tGestureId gestureId, const cMovement & movement) const
Inform whether or not the movement is recognised according to the gesture
Returns:
true if the gesture is recognised, false otherwise
Parameters:
gestureId Gesture to be analysed
movement Movement to be analysed
Definition at line 914 of file GestureRecogniser.cpp.
References AGR::cHMM::forward(), getGesture(), AGR::cHMM::getObservationSize(), AGR::cMovement::getSize(), AGR::cHMM::isReady(), and isRecognised().
tGestureId AGR::cGestureRecogniser::closerGesture (const cMovement & movement) const
Find the closer gesture to a movement
Note:
The probability used is weighed with the observation size
Returns:
the id of the gesture with the highest probability
Parameters:
movement Movement to be analysed
Definition at line 940 of file GestureRecogniser.cpp.
References AGR::cHMM::forward(), AGR::cHMM::getObservationSize(), AGR::cMovement::getSize(), isReady(), m_gestureBuffer, and m_gestureSize.
float AGR::cGestureRecogniser::gestureLikelihood (const tGestureId gestureId, const cMovement & movement) const
Get the probability likelihood of the differents gestures of a movement
Note:
The result is weighed with the observation size
Parameters:
gestureId Gesture to be analysed
movement Movement to be analysed
Definition at line 969 of file GestureRecogniser.cpp.
References AGR::cHMM::forward(), getGesture(), AGR::cHMM::getObservationSize(), AGR::cMovement::getSize(), AGR::cHMM::isReady(), and m_gestureBuffer.
bool AGR::cGestureRecogniser::gesturesLikelihood (const cMovement & movement, float * probabilityVector) const
Get the probability likelihood of the differents gestures of a movement
Note:
The probability returned are weighed with their observation size
Parameters:
movement Movement to be analysed
probabilityVector Array for storing the probability likelihood, need to be the same size as the gesture buffer
Definition at line 998 of file GestureRecogniser.cpp.
References AGR::cHMM::forward(), getGesture(), AGR::cHMM::getObservationSize(), AGR::cHMM::isReady(), m_gestureBuffer, and m_gestureSize.
tGestureId AGR::cGestureRecogniser::addGesture (const cGesture & gesture, tVocabularyId vocabularyId = -1, const char * gestureName = NULL)
Add a gesture into the gesture buffer.
Returns:
-1 if the function failed, the id of the gesture otherwith.
Note:
If a vocabularyId is provided, the vocabulary object is then linked with the HMM.
If the vocabularyId is negative, the vocabulary associated the gesture need to be inside the vocabulary buffer.
The input gesture is copied in the buffer.
Parameters:
gesture Gesture to be added
vocabularyId Id of the vocabulary associated with the gesture, see function's note
gestureName Name of the gesture if wanted
Definition at line 390 of file GestureRecogniser.cpp.
References AGR::cHMM::assignVocabulary(), AGR::cHMM::getVocabulary(), getVocabulary(), AGR::cHMM::isReady(), isReady(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, and m_vocabularySize.
tGestureId AGR::cGestureRecogniser::loadGesture (const char * gestureFile, tVocabularyId vocabularyId, const char * gestureName = NULL)
Load a gesture from a file
Returns:
-1 if the function failed, the id of the gesture otherwith.
Note:
The vocabularyId need to be provided, in order to be linked with the gesture.
Parameters:
gestureFile File where the gesture is read
vocabularyId Id of the vocabulary associated with the gesture
gestureName Name of the gesture if wanted
Definition at line 481 of file GestureRecogniser.cpp.
References AGR::cHMM::clear(), getVocabulary(), isReady(), load(), m_gestureBuffer, m_gestureNameBuffer, and m_gestureSize.
bool AGR::cGestureRecogniser::saveGesture (const tGestureId gestureId, const char * gestureFile, const bool binary = false) const
Save a gesture to a file
Note:
The gesture name is not saved
Returns:
Success
Parameters:
gestureId Id of the gesture to be saved
gestureFile Name of the file to save in
binary Specify whether saving in binary of ASCII format
Definition at line 543 of file GestureRecogniser.cpp.
References getGesture(), and AGR::cHMM::save().
bool AGR::cGestureRecogniser::removeGesture (const tGestureId gestureId)
Remove a gesture from the buffer
Returns:
Success
Note:
The gesture is not deleted, but put in an not initialised state for being reused later
Parameters:
gestureId Id of the gesture to be removed
Definition at line 563 of file GestureRecogniser.cpp.
References AGR::cHMM::clear(), isReady(), m_gestureBuffer, and m_gestureSize.
cGesture * AGR::cGestureRecogniser::getGesture (const tGestureId gestureId) const
Get a gesture in the gesture buffer by its id.
Returns:
NULL if failed, the requested gesture otherwise
Parameters:
gestureId Id of the gesture
Definition at line 582 of file GestureRecogniser.cpp.
References m_gestureBuffer, and m_gestureSize.
Referenced by gestureLikelihood(), gesturesLikelihood(), recognise(), recogniseGesture(), and saveGesture().
const char * AGR::cGestureRecogniser::getGestureName (const tGestureId gestureId) const
Get a gesture name by its id.
Returns:
NULL if failed, the requested gesture name otherwise
Parameters:
gestureId Id of the gesture
Definition at line 600 of file GestureRecogniser.cpp.
References m_gestureNameBuffer, and m_gestureSize.
tGestureId AGR::cGestureRecogniser::findGestureByName (const char * gestureName) const
Find a gesture id by its name.
Returns:
-1 if not found or failed, the requested gesture id otherwise
Parameters:
gestureName Name of the gesture
Definition at line 619 of file GestureRecogniser.cpp.
References m_gestureNameBuffer, and m_gestureSize.
tVocabularyId AGR::cGestureRecogniser::addVocabulary (const cVocabulary & vocabulary, const char * vocName = NULL)
Add a vocabulary object to the buffer
Returns:
-1 if the function failed, the id of the vocabulary otherwith.
Note:
The input vocabulary is copied in the buffer.
Parameters:
vocabulary Vocabulary to be added
vocName Name for the vocabulary if wanted
Definition at line 646 of file GestureRecogniser.cpp.
References isReady(), AGR::cVocabulary::isReady(), m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
tVocabularyId AGR::cGestureRecogniser::loadVocabulary (const char * vocabularyFile, const char * vocName = NULL)
Load a vocabulary from a file
Returns:
-1 if the function failed, the id of the gesture otherwith.
Parameters:
vocabularyFile File where the vocabulary is read
vocName Name for the vocabulary if wanted
Definition at line 699 of file GestureRecogniser.cpp.
References AGR::cVocabulary::clear(), isReady(), load(), m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
bool AGR::cGestureRecogniser::saveVocabulary (const tVocabularyId vocabularyId, const char * vocabularyFile, const bool binary = false) const
Save a vocabulary to a file
Note:
The vocabulary name is not saved
Returns:
Success
Parameters:
vocabularyId Id of the vocabulary to be saved
vocabularyFile Name of the file to save in
binary Specify whether saving in binary of ASCII format
Definition at line 755 of file GestureRecogniser.cpp.
References getVocabulary(), and AGR::cVocabulary::save().
bool AGR::cGestureRecogniser::removeVocabulary (const tVocabularyId vocabularyId)
Remove a vocabulary from the buffer
Returns:
Success
Note:
The vocabulary is not deleted, but put in an not initialised state for being reused later
Parameters:
vocabularyId Id of the vocabulary to be removed
Definition at line 775 of file GestureRecogniser.cpp.
References AGR::cVocabulary::clear(), getVocabulary(), isReady(), m_gestureBuffer, m_gestureSize, m_vocabularyBuffer, and m_vocabularySize.
cVocabulary * AGR::cGestureRecogniser::getVocabulary (const tVocabularyId vocabularyId) const
Get a vocabulary in the vocabulary buffer by its id.
Returns:
NULL if failed, the requested vocabulary otherwise
Parameters:
vocabularyId Id of the vocabulary
Definition at line 813 of file GestureRecogniser.cpp.
References m_vocabularyBuffer, and m_vocabularySize.
Referenced by addGesture(), loadASCII(), loadBinary(), loadGesture(), removeVocabulary(), resize(), and saveVocabulary().
const char * AGR::cGestureRecogniser::getVocabularyName (const tVocabularyId vocabularyId) const
Get a vocabulary name by its id.
Returns:
NULL if failed, the requested vocabulary name otherwise
Parameters:
vocabularyId Id of the vocabulary
Definition at line 831 of file GestureRecogniser.cpp.
References m_vocabularyNameBuffer, and m_vocabularySize.
tVocabularyId AGR::cGestureRecogniser::findVocabularyByName (const char * vocName) const
Find a gesture id by its name.
Returns:
-1 if not found or failed, the requested vocabulary id otherwise
Parameters:
vocName Name of the vocabulary
Definition at line 850 of file GestureRecogniser.cpp.
References m_gestureSize, and m_vocabularyNameBuffer.
cMovementRecogniser* AGR::cGestureRecogniser::getMovementRecogniser () [inline]
Movement recogniser size accessor
Returns:
A pointer to the movement recogniser object
Definition at line 120 of file GestureRecogniser.h.
References m_movementRecogniser.
bool AGR::cGestureRecogniser::loadASCII (std::ifstream & file) [protected]
Load from an ASCII file
Returns:
Success
Definition at line 1031 of file GestureRecogniser.cpp.
References AGR::cHMM::assignVocabulary(), clear(), getVocabulary(), AGR::cHMM::loadASCII(), AGR::cVocabulary::loadASCII(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
Referenced by load().
bool AGR::cGestureRecogniser::saveASCII (std::ofstream & file) const [protected]
Save from an ASCII file
Returns:
Success
Definition at line 1135 of file GestureRecogniser.cpp.
References isReady(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, m_vocabularySize, AGR::cHMM::saveASCII(), and AGR::cVocabulary::saveASCII().
Referenced by save().
bool AGR::cGestureRecogniser::loadBinary (std::ifstream & file) [protected]
Load from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 1233 of file GestureRecogniser.cpp.
References AGR::cHMM::assignVocabulary(), getVocabulary(), AGR::cHMM::loadBinary(), AGR::cVocabulary::loadBinary(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, and m_vocabularySize.
Referenced by load().
bool AGR::cGestureRecogniser::saveBinary (std::ofstream & file) const [protected]
Save from a binary file
Returns:
Success
Todo:
Endianness
Definition at line 1340 of file GestureRecogniser.cpp.
References isReady(), m_gestureBuffer, m_gestureNameBuffer, m_gestureSize, m_vocabularyBuffer, m_vocabularyNameBuffer, m_vocabularySize, AGR::cHMM::saveBinary(), and AGR::cVocabulary::saveBinary().
Referenced by save().
bool AGR::cGestureRecogniser::isRecognised (const cGesture & gesture, const float probability) const [protected]
Decide according to the probability whether or not the provided gesture is recognised
Returns:
true if recognised, false otherwise
Note:
The probability has to be normalised, i.e. probability = gesture->forward(movement) * gesture->getObservationSize()
Parameters:
gesture Gesture to be analysed
probability Gesture's probability (see note)
Definition at line 1446 of file GestureRecogniser.cpp.
References AGR::cHMM::getMeanProbabilityWeighted(), and AGR::cHMM::getVarianceProbabilityWeighted().
Referenced by recognise(), and recogniseGesture().
Member Data Documentation
cVocabulary* AGR::cGestureRecogniser::m_vocabularyBuffer [protected]
Vocabulary buffer
Definition at line 127 of file GestureRecogniser.h.
Referenced by addGesture(), addVocabulary(), clear(), getVocabulary(), init(), isReady(), loadASCII(), loadBinary(), loadVocabulary(), removeVocabulary(), resize(), saveASCII(), and saveBinary().
cGesture* AGR::cGestureRecogniser::m_gestureBuffer [protected]
Gesture buffer
Definition at line 128 of file GestureRecogniser.h.
Referenced by addGesture(), clear(), closerGesture(), gestureLikelihood(), gesturesLikelihood(), getGesture(), init(), isReady(), loadASCII(), loadBinary(), loadGesture(), removeGesture(), removeVocabulary(), resize(), saveASCII(), and saveBinary().
char** AGR::cGestureRecogniser::m_vocabularyNameBuffer [protected]
Vocabulary names buffer
Definition at line 129 of file GestureRecogniser.h.
Referenced by addVocabulary(), clear(), findVocabularyByName(), getVocabularyName(), init(), loadASCII(), loadBinary(), loadVocabulary(), resize(), saveASCII(), and saveBinary().
char** AGR::cGestureRecogniser::m_gestureNameBuffer [protected]
Gesture names buffer
Definition at line 130 of file GestureRecogniser.h.
Referenced by addGesture(), clear(), findGestureByName(), getGestureName(), init(), loadASCII(), loadBinary(), loadGesture(), resize(), saveASCII(), and saveBinary().
unsigned int AGR::cGestureRecogniser::m_vocabularySize [protected]
Size of the vocabulary buffer
Definition at line 131 of file GestureRecogniser.h.
Referenced by addGesture(), addVocabulary(), clear(), getNumberVocabulary(), getVocabulary(), getVocabularyName(), init(), loadASCII(), loadBinary(), loadVocabulary(), removeVocabulary(), resize(), saveASCII(), and saveBinary().
unsigned int AGR::cGestureRecogniser::m_gestureSize [protected]
Size of the gesture buffer
Definition at line 132 of file GestureRecogniser.h.
Referenced by addGesture(), clear(), closerGesture(), findGestureByName(), findVocabularyByName(), gesturesLikelihood(), getGesture(), getGestureName(), getNumberGesture(), init(), loadASCII(), loadBinary(), loadGesture(), recognise(), removeGesture(), removeVocabulary(), resize(), saveASCII(), and saveBinary().
cMovementRecogniser AGR::cGestureRecogniser::m_movementRecogniser [protected]
Movement Recogniser optional component
Definition at line 144 of file GestureRecogniser.h.
Referenced by clear(), and getMovementRecogniser().
The documentation for this class was generated from the following files:
latest/include/GestureRecogniser.h
latest/src/GestureRecogniser.cpp