AGR: AGR::cClustering Class Reference
AGR::cClustering
AGR::cClustering Class Reference
cClustering class.
#include <Clustering.h>
Public Member Functions
cClustering ()
virtual ~cClustering ()
virtual bool initialise (const unsigned int size, cVector3int *ptBuffer)
virtual void clear ()
Static Public Member Functions
static bool createNormalisedVectors (const cMovement *movementArray, const unsigned int nbMovement, cMovement **ptNormalisedMovementArray, cMovement *ptAverageMovement, cMovement *ptAllMovementsPoints, unsigned int *ptMovementNormalisedSize=NULL)
Protected Attributes
unsigned int m_size
cVector3int * m_buffer
Friends
class ::cTestClustering
Detailed Description
cClustering class.
Definition at line 25 of file Clustering.h.
Constructor & Destructor Documentation
AGR::cClustering::cClustering ()
Constructor
Definition at line 19 of file Clustering.cpp.
AGR::cClustering::~cClustering () [virtual]
Destructor
Definition at line 27 of file Clustering.cpp.
References clear().
Member Function Documentation
bool AGR::cClustering::initialise (const unsigned int size, cVector3int * ptBuffer) [virtual]
Initialise the necessary values
Returns:
Success
Parameters:
size Size of the buffer (Number of clusters)
ptBuffer Pointer to the buffer to be manipulated
Definition at line 47 of file Clustering.cpp.
References m_buffer, and m_size.
Referenced by AGR::cVocabulary::copy(), AGR::cHMM::createHMM(), AGR::cVocabulary::cVocabulary(), AGR::cVocabulary::initialise(), AGR::cVocabulary::loadASCII(), and AGR::cVocabulary::loadBinary().
void AGR::cClustering::clear () [virtual]
Clear the values
Definition at line 36 of file Clustering.cpp.
References m_buffer, and m_size.
Referenced by AGR::cHMM::createHMM(), and ~cClustering().
bool AGR::cClustering::createNormalisedVectors (const cMovement * movementArray, const unsigned int nbMovement, cMovement ** ptNormalisedMovementArray, cMovement * ptAverageMovement, cMovement * ptAllMovementsPoints, unsigned int * ptMovementNormalisedSize = NULL) [static]
Create normalised vectors and their average vectors
Returns:
Success
Parameters:
movementArray Array containing the movement to be processed
nbMovement Number of movement in the array
ptNormalisedMovementArray Array used to store the normalised movement
ptAverageMovement Average movement
ptAllMovementsPoints Store all the points of all the previous movements
ptMovementNormalisedSize Size used for normalised vectors, two time the average observation size (used if the pointer is not NULL)
Definition at line 67 of file Clustering.cpp.
References AGR::cMovement::changeVectorSize(), AGR::cMovement::getData(), AGR::cMovement::getSize(), AGR::cMovement::initialise(), and AGR::cMovement::modifyBuffer().
Referenced by AGR::cKmeansClustering::createClusters(), and AGR::cHMM::createHMM().
Member Data Documentation
unsigned int AGR::cClustering::m_size [protected]
Number of clusters (k)
Definition at line 50 of file Clustering.h.
Referenced by clear(), AGR::cKmeansClustering::closerCluster(), AGR::cKmeansClustering::createClusters(), and initialise().
cVector3int* AGR::cClustering::m_buffer [protected]
Pointer to the buffer containing the clusters
Definition at line 51 of file Clustering.h.
Referenced by clear(), AGR::cKmeansClustering::closerCluster(), AGR::cKmeansClustering::clusterise(), AGR::cKmeansClustering::createClusters(), initialise(), and AGR::cKmeansClustering::~cKmeansClustering().
The documentation for this class was generated from the following files:
latest/include/Clustering.h
latest/src/Clustering.cpp