AGR: AGR::cMovementRecogniser Class Reference
AGR::cMovementRecogniser
AGR::cMovementRecogniser Class Reference
Base class for movement recognition.
#include <MovementRecogniser.h>
Public Types
enum eMovementState {
eMovementERROR = -1, eMovementNone = 0, eMovementInProgress, eMovementManualInProgress,
eMovementFinished, eMovementManualFinished, eMovementOutOfBuffer, eMovementManualOutOfBuffer
}
Public Member Functions
cMovementRecogniser ()
virtual ~cMovementRecogniser ()
void clear ()
bool initialise (unsigned int nbDevices, unsigned int maxMovementSize=50)
bool isReady () const
eMovementState addAcceleration (const tAGRDeviceId deviceId, const cVector3int &acceleration)
eMovementState getState (const tAGRDeviceId deviceId) const
bool getMovement (const tAGRDeviceId deviceId, cMovement *ptMovement) const
bool manualRecognitionStart (const tAGRDeviceId deviceId)
bool manualRecognitionStop (const tAGRDeviceId deviceId, cMovement *ptMovement)
unsigned int getNbDevices () const
unsigned int getMaxMovementSize () const
Protected Member Functions
virtual eMovementState process (const tAGRDeviceId deviceId, const cVector3int &acceleration)
Protected Attributes
sDeviceMovement * m_devicesArray
unsigned int m_nbDevices
unsigned int m_maxMovementSize
Friends
class ::cTestMovementRecogniser
Classes
struct sDeviceMovement
Detailed Description
Base class for movement recognition.
Note:
If the recognition algorithm need to be changed, you can either modify process() or overload it in a child class.
Definition at line 30 of file MovementRecogniser.h.
Member Enumeration Documentation
enum AGR::cMovementRecogniser::eMovementState
Enumeration of the differents movement recognition state a device can be
Note:
When receiving an OutOfBuffer state, the next iteration will overwrite the values. Before that calling getMovement() could be used by the application for storing these values
Enumerator:
eMovementERROR An error occured
eMovementNone No movement recognised
eMovementInProgress A movement is being recognised but not yet finished
eMovementManualInProgress A movement is currently manualy recognised
eMovementFinished A movement has been recognised
eMovementManualFinished End of the manual movement recognition
eMovementOutOfBuffer Movement out of buffer (size bigger than maxMovementSize). see eMovementState note
eMovementManualOutOfBuffer Manual recognition movement out of buffer (size bigger than maxMovementSize). see eMovementState note
Definition at line 41 of file MovementRecogniser.h.
Constructor & Destructor Documentation
AGR::cMovementRecogniser::cMovementRecogniser ()
Constructor
Definition at line 20 of file MovementRecogniser.cpp.
AGR::cMovementRecogniser::~cMovementRecogniser () [virtual]
Destructor
Definition at line 29 of file MovementRecogniser.cpp.
References clear().
Member Function Documentation
void AGR::cMovementRecogniser::clear ()
Clear all the data
Definition at line 38 of file MovementRecogniser.cpp.
References AGR::cMovementRecogniser::sDeviceMovement::m_array, m_devicesArray, m_maxMovementSize, and m_nbDevices.
Referenced by AGR::cGestureRecogniser::clear(), and ~cMovementRecogniser().
bool AGR::cMovementRecogniser::initialise (unsigned int nbDevices, unsigned int maxMovementSize = 50)
Initialise the cMovementRecogniser object
Returns:
Success
Parameters:
nbDevices Number of devices to be used
maxMovementSize Maximum size of a movement
Definition at line 60 of file MovementRecogniser.cpp.
References eMovementNone, AGR::cMovementRecogniser::sDeviceMovement::m_array, AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, AGR::cMovementRecogniser::sDeviceMovement::m_idStartMov, m_maxMovementSize, and m_nbDevices.
bool AGR::cMovementRecogniser::isReady () const
Inform if the movement recogniser is ready to be used.
Returns:
True if ready, false if not
Definition at line 96 of file MovementRecogniser.cpp.
References m_devicesArray, m_maxMovementSize, and m_nbDevices.
Referenced by addAcceleration(), getMovement(), getState(), manualRecognitionStart(), and manualRecognitionStop().
cMovementRecogniser::eMovementState AGR::cMovementRecogniser::addAcceleration (const tAGRDeviceId deviceId, const cVector3int & acceleration)
Add a new acceleration data to a device.
Returns:
The movement state
Parameters:
deviceId Devices to be manipulated
acceleration New acceleration to be processed
Definition at line 113 of file MovementRecogniser.cpp.
References eMovementERROR, eMovementManualInProgress, eMovementManualOutOfBuffer, isReady(), AGR::cMovementRecogniser::sDeviceMovement::m_array, AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, m_maxMovementSize, m_nbDevices, and process().
cMovementRecogniser::eMovementState AGR::cMovementRecogniser::getState (const tAGRDeviceId deviceId) const
Get the state of a device movement.
Returns:
The device movement state
Parameters:
deviceId Devices to be manipulated
Definition at line 161 of file MovementRecogniser.cpp.
References eMovementERROR, isReady(), AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, and m_nbDevices.
bool AGR::cMovementRecogniser::getMovement (const tAGRDeviceId deviceId, cMovement * ptMovement) const
Get the movement stored in a device movement.
Returns:
Success
Parameters:
deviceId Devices to be manipulated
ptMovement cMovement object where the movement will be stored
Definition at line 182 of file MovementRecogniser.cpp.
References AGR::cMovement::initialise(), isReady(), AGR::cMovementRecogniser::sDeviceMovement::m_array, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, AGR::cMovementRecogniser::sDeviceMovement::m_idStartMov, m_maxMovementSize, and m_nbDevices.
bool AGR::cMovementRecogniser::manualRecognitionStart (const tAGRDeviceId deviceId)
Start the manual recognition for a device
Returns:
Success
Note:
This could be used for manualy start a movement (eg. when pressing a button)
Anything that was been done earlier will be canceled by this action (like automatic or manual recognition)
See also:
manualRecognitionStop
Parameters:
deviceId Devices to be manipulated
Definition at line 242 of file MovementRecogniser.cpp.
References eMovementManualInProgress, isReady(), AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, AGR::cMovementRecogniser::sDeviceMovement::m_idStartMov, and m_nbDevices.
bool AGR::cMovementRecogniser::manualRecognitionStop (const tAGRDeviceId deviceId, cMovement * ptMovement)
Stop the manual recognition for a device
Returns:
Success
Note:
Only something that has started may be stopped...
See also:
manualRecognitionStart
Parameters:
deviceId Devices to be manipulated
ptMovement cMovement object where the movement will be stored
Definition at line 269 of file MovementRecogniser.cpp.
References eMovementManualFinished, eMovementManualInProgress, eMovementManualOutOfBuffer, eMovementNone, AGR::cMovement::initialise(), isReady(), AGR::cMovementRecogniser::sDeviceMovement::m_array, AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, AGR::cMovementRecogniser::sDeviceMovement::m_idStartMov, and m_nbDevices.
unsigned int AGR::cMovementRecogniser::getNbDevices () const [inline]
Number of devices accessor
Returns:
The number of devices
Definition at line 79 of file MovementRecogniser.h.
References m_nbDevices.
unsigned int AGR::cMovementRecogniser::getMaxMovementSize () const [inline]
Maximum size of a movement accessor
Returns:
The maximum size of a movement
Definition at line 88 of file MovementRecogniser.h.
References m_maxMovementSize.
cMovementRecogniser::eMovementState AGR::cMovementRecogniser::process (const tAGRDeviceId deviceId, const cVector3int & acceleration) [protected, virtual]
Process the movement recognition
Returns:
The device movement state
Note:
This function has been done using empirical testing. Feel free to modify it or overload it
Definition at line 308 of file MovementRecogniser.cpp.
References eMovementFinished, eMovementInProgress, eMovementNone, eMovementOutOfBuffer, AGR::cMovementRecogniser::sDeviceMovement::m_array, AGR::cMovementRecogniser::sDeviceMovement::m_currentState, m_devicesArray, AGR::cMovementRecogniser::sDeviceMovement::m_idEndMov, AGR::cMovementRecogniser::sDeviceMovement::m_idStartMov, m_maxMovementSize, AGR::cVector3int::x, AGR::cVector3int::y, and AGR::cVector3int::z.
Referenced by addAcceleration().
Member Data Documentation
sDeviceMovement* AGR::cMovementRecogniser::m_devicesArray [protected]
Store the devices informations
Definition at line 110 of file MovementRecogniser.h.
Referenced by addAcceleration(), clear(), getMovement(), getState(), initialise(), isReady(), manualRecognitionStart(), manualRecognitionStop(), and process().
unsigned int AGR::cMovementRecogniser::m_nbDevices [protected]
Number of devices
Definition at line 111 of file MovementRecogniser.h.
Referenced by addAcceleration(), clear(), getMovement(), getNbDevices(), getState(), initialise(), isReady(), manualRecognitionStart(), and manualRecognitionStop().
unsigned int AGR::cMovementRecogniser::m_maxMovementSize [protected]
Maximum size of a movement (used for sDeviceMovement::m_array)
Definition at line 112 of file MovementRecogniser.h.
Referenced by addAcceleration(), clear(), getMaxMovementSize(), getMovement(), initialise(), isReady(), and process().
The documentation for this class was generated from the following files:
latest/include/MovementRecogniser.h
latest/src/MovementRecogniser.cpp